# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e1f38734508aad7721c1af96704b9e06c1da63ac00f266995b13a7753c0c7c5d265d512f3e93d44384938a3ec68faddff68d80b1bce589d744e188cffe5860

test:
  secret_key_base: 534a4e63da622d6c954ee63d4b33286fed326d8babd85ed80c01e0c35fe7e14012629ed61d9dfdfa183207ede2fed524c032cac58851832f8d2c3448d72edd53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
